# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Tumbleweed.x86_64"

  # Forwarded ports
  config.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"
  
  config.vm.provider "virtualbox" do |vb|
    # the machine name
    vb.name = "flaskapp-POC"
  end

  # install apache and flask
  config.vm.provision "shell", path: "install.sh"
  config.vm.provision "file", source: "localhost.conf", destination: "/etc/apache2/vhosts.d/localhost.conf"
  config.vm.provision "file", source: "app.py", destination: "/home/flaskappuser/flaskapp/app.py"

end
